version: '3'

services:
  mysql:
    image: library/mysql:8.0.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest1234
      MYSQL_ROOT_PASSWORD: nest1234
      TZ: Asia/Seoul
    ports:
      - 33061:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql